services:
  attendance_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7009:3000"
    command: npm start
    env_file:
      - .env.${ENV_MODE}
    environment:
      - TZ=Asia/Jakarta
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
